#!/bin/bash
echo "10.0.1.4:/nfsv3     /nfsv3 nfs     rsize=262144,wsize=262144" >> /etc/fstab
yum install fio vim nfs-utils git ksh  sysstat -y
mkdir  /nfsv3
sysctl -a > /etc/sysctl.conf.default
echo "# In unit of bytes
net.core.rmem_max = 134217728
net.core.wmem_max = 134217728
net.core.wmem_default = 2097152
net.core.rmem_default = 2097152
net.ipv4.tcp_rmem = 4096 87380 67108864
net.ipv4.tcp_wmem = 4096 65536 67108864
net.core.optmem_max = 2048000
net.core.somaxconn = 65535
# #
# # Set congestion control
# # If not listed try /sbin/modprobe tcp_htcp, then load with this tune
net.ipv4.tcp_congestion_control=htcp
# #
# # Recommended for CentOS7+/Debian8+ hosts
# #
# #net.core.default_qdisc = fq#
# #
# # In unit of 4k pages
# # Min = 16MiB, Def=350MiB, Max=16GiB
net.ipv4.tcp_mem = 4096 89600 4194304
# #
# # Recommended for hosts with jumbo frames enabled
# # net.ipv4.tcp_mtu_probing=1
# #
net.ipv4.tcp_window_scaling = 1
net.ipv4.tcp_timestamps = 0
net.ipv4.tcp_sack = 0
net.ipv4.tcp_dsack = 0
net.ipv4.tcp_fack = 0
net.ipv4.tcp_no_metrics_save = 1
net.ipv4.route.flush = 1
net.ipv4.tcp_low_latency = 1
net.ipv4.ip_local_port_range = 1024 65000
net.ipv4.tcp_slow_start_after_idle = 0
net.core.netdev_max_backlog = 300000
sunrpc.tcp_max_slot_table_entries=128
sunrpc.tcp_slot_table_entries=128

# #
# # Filesystem tune
#
vm.dirty_expire_centisecs = 100
vm.dirty_writeback_centisecs = 100
vm.dirty_ratio = 5
vm.dirty_background_ratio = 1
" > /etc/sysctl.conf
sysctl -p /etc/sysctl.conf


mount -a
git -C /nfsv3 clone https://github.com/mchad1/poc.git

# Tuned
mkdir /usr/lib/tuned/sas-perf
cp /nfsv3/poc/tuned.conf /usr/lib/tuned/sas-perf
tuned-adm profile sas-perf
