#!/bin/ksh
for connect in 1 2 4 8 16; do
    umount /nfsv3
    mount 10.0.1.4:/nfsv31 /nfsv3 -o rsize=262144,wsize=262144,nconnect=$connect
    for queue in 0 1 2 3 ; do
        ./set_irq_affinity_bynode.sh  $queue eth1;  for work in 0 100; do
             if [[ $work == 0 ]]; then
                direction=Write
             else
                direction=Read
             fi;
             taskset -c 31 fio /nfsv3/poc/fio.ini --rwmixread=$work --iodepth=80 --nrfiles=$1 -o /nfsv3/poc/fio-platform-results/l32v2-irq${queue}-nconnect${connect}-vm1-4k${direction}-${1}files-iodpeth80;
             taskset -c 31 fio /nfsv3/poc/fio.ini --rwmixread=$work --iodepth=120 --nrfiles=$1 -o /nfsv3/poc/fio-platform-results/l32v2-irq${queue}-nconnect${connect}-vm1-4k${direction}-${1}files-iodpeth120;
         done;
     done
done
